#!/usr/bin/env bash
#
# run_vfmig_image_test.sh -- build + run the no-hardware unit test for
# the mlx5_sriov_vfmig plugin's on-disk image helpers (vf_image.c).
#
# This gate needs NO tracked VF, NO running criu, and NO plugin .so: it
# compiles vf_image.c and the generated image pb-c straight into a small
# test binary (vfmig_image_test.c) that round-trips records + a blob
# through the real code against a temp directory. It is the earliest
# functional validation in the VF-firmware-state build-up -- everything
# up to here (presence detect, claim, claimed-VF cache) is only
# observable with a tracked VF, but the image format is not.
#
# Usage:  ./run_vfmig_image_test.sh
#
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
PLUGIN_DIR="$ROOT/plugins/rdma/mlx5_sriov_vfmig"
PBC="$ROOT/images/mlx5_vfmig.pb-c.c"
BIN="$(mktemp -u /tmp/vfmig_image_test.XXXXXX)"

case "$(uname -m)" in
x86_64) ARCH=x86 ;;
aarch64) ARCH=aarch64 ;;
*) ARCH="$(uname -m)" ;;
esac

# The image pb-c is generated by the top-level build; regenerate on demand.
if [ ! -f "$PBC" ]; then
	echo "== generating $PBC =="
	make -C "$ROOT" images/mlx5_vfmig.pb-c.c >/dev/null
fi

echo "== compiling vfmig_image_test =="
# Use -iquote (not -I) for the in-tree dirs so they only satisfy
# #include "..." and never shadow system <...> headers (e.g. <fcntl.h>,
# <linux/types.h>) -- the same reason the plugin Makefile uses -iquote.
cc -O2 -Wall -g \
	-iquote"$ROOT" \
	-iquote"$ROOT/include" \
	-iquote"$ROOT/criu/include" \
	-iquote"$ROOT/criu/arch/$ARCH/include" \
	-iquote"$PLUGIN_DIR" \
	"$HERE/vfmig_image_test.c" \
	"$PLUGIN_DIR/vf_image.c" \
	"$PBC" \
	-lprotobuf-c \
	-o "$BIN"

echo "== running vfmig_image_test =="
rc=0
"$BIN" || rc=$?
rm -f "$BIN"

if [ "$rc" -ne 0 ]; then
	echo "VFMIG IMAGE TEST: FAIL (rc=$rc)"
	exit "$rc"
fi
echo "VFMIG IMAGE TEST: PASS"
